version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    hostname: ${DB_HOST:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_NAME:-postgres}",
          "-U",
          "${DB_USER:-postgres}"
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build:
      context: ./
      target: app
      args:
        SERVICE_NAME: api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env